server:
  port: 10080

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8
  application:
    name: service-media
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # 配置数据源
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql:///ymcc-media?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource # 指定连接池
mybatis-plus:
  mapper-locations: classpath:cn/itsource/mapper/*Mapper.xml  # 扫描mapper.xml
# type-aliases-package: cn.itsource.domain 不用别名效率高

media:
  upload-base-dir: "C:/Users/blank/Desktop/test" #分片上传地址
  #oad‐location: "d:/"  #合并之后的视频文件存储地址
  ffmpeg‐path: "D:/itEnvironment/ffmpeg/bin/ffmpeg.exe" #ffmpeg视频工具安装地址
  rtmp: "rtmp://115.159.88.63:1935/live/" #推流到云服务器的地址
  play: "http://115.159.88.63:8080/live/" #播放地址

rocketmq:
  name-server: 127.0.0.1:9876
  # 是否开启自动配置
  producer:
    # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    group: "service-media-producer"
    # 消息最大长度 默认 1024 * 4 (4M)
    max-message-size: 4096
    # 发送消息超时时间，默认 3000
    send-message-timeout: 3000
    # 发送消息失败重试次数，默认2
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2









